language: node_js
node_js:
- node
env:
  global:
    secure: E67Wv+XZddBZRK6LueeY+ZPgZGBEQDRASytL6bG577zvinAvsGWyF60wHpAPaThRR76Qczkt29jN42+MyeP0dUkR+MWIPBeiFAw6eqCglU3Iq6uAnlyalw1C0FeRmiaQuNtqeUvhqUXpikk+o6cuUK0Yw3+Kf1pNta+HMrB4QppNCSxDO0TqI318zcLtwugaFCQQ3zffeIhYut/riYDPDUIKlrMK8rFEToJXwzHyRLAw19TKDYHHJ7O+8xjIrItcyTibtw6mwHzz1COJCHtOR2He1wsvGG3jhi+5Ey+khypoCgmjuofY0wIRMMeZ9X6TG2eu5y1QBBQK73ohwH9X481yRxEh6qXBWl/6Dg9Fu5hRzfUCcXQ+qSOLBka0HIWDANCplj1akYkhkpT+B1y8fPx6Gv4bRdKTMJO8BhMou+LF451tAHqbky50iO2upBQPCdPFhkXhxtbbtfLVUX7ORks3So6GNlNjWQLObMuUIKRR6pxwyZ9lvu7nqgdR1Bz4ZhiERIWRWvdcxrCRakOhsnQvalmkcHsBw6/k5JlkCMG/diPPGAjaEKjeJmf5t5GIrgAwwUzB6VwE5rBHwOz4D/ufZBlHIF/IAWFIOwqA7F5N7/oLfP8+5ek3X3UCfERDdA6gy0ikNqMD30gpC6IvAb05Tya0/iWmUBe1n3PzcjI=
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - xvfb
script:
- npm run build
- npm run coverage:travis
- npm run e2e:travis
- npm run lint
before_install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
